---
title: "Prism plot flipbook"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = FALSE, fig.retina = 3)
library(tidyverse)
library(lubridate)
library(here)
library(janitor)
library(plotly)
library(flipbookr)
library(beepr) #long analysis; get some coffee, and comeback when ready
library(gghighlight)
library(patchwork)

prism_url <- "https://ndownloader.figshare.com/files/17741420" #primary-screen-replicate-collapsed-logfold-change.csv
prismmeta_url <- "https://ndownloader.figshare.com/files/20237715" #primary-screen-replicate-collapsed-treatment-info.csv

prism <- read_csv(prism_url, col_names = TRUE) %>% 
  clean_names()

prism_long <- prism %>% 
  #slice(1:10) %>% 
  pivot_longer(cols = -x1, names_to = "drug", values_to = "log2fc")

prism_meta <- read_csv(prismmeta_url, col_names = TRUE) %>% 
  clean_names()

prism_meta %>% 
  mutate(drug_meta = str_to_lower(broad_id)) %>% 
  mutate(drug_meta = str_replace_all(drug_meta, "-", "_")) -> prism_meta_new

prism_long %>% 
  mutate(drug_short = str_sub(drug, 1, 22)) %>% 
  left_join(prism_meta_new, by = c("drug_short" = "drug_meta")) -> prism_join

prism_bigfc <- filter(prism_join, log2fc <= -2)
```

```{r rainfall_plot, eval = FALSE}
prism_bigfc %>% 
ggplot() +
aes(x = phase) +
aes(y = log2fc) +
geom_jitter(
aes(color= 
str_match(moa,"tubulin polymerization inhibitor")),
    alpha = 0.1
) +
scale_color_manual(
  values = c("darkred")
) +  
guides(
  color= "none") +
theme_bw() +
labs(
x = "Phase",
title = "Rainfall Plot",
subtitle = "Plotting Prism data",
caption = "By: [Insert your name]")  
```
---

`r chunk_reveal("rainfall_plot", break_type = "auto")`

---




